version: '3.7'
services:
  php:
    build: php
    volumes:
      - ./source:/var/www/html
    networks:
      - appnet

  nginx:
    build: nginx
    ports:
      - 80:80
    volumes:
      - ./source:/var/www/html
    networks:
      - appnet

  db:
    build: mysql
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento2
      MYSQL_USER: magento2
      MYSQL_PASSWORD: magento2
    networks:
      - appnet

volumes:
  db_data:
    driver: "local"

networks:
  appnet:
    driver: "bridge"