version: '3.7'

services:
  nginx:
    build: ./nginx
    ports:
      - 80


  php:
    build: ./php
    ports:
      - 9000

  db:
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306